Mean <- apply(quantitative_data, 2, mean, na.rm = TRUE)
Var  <- apply(quantitative_data, 2, var, na.rm = TRUE)
Sd   <- apply(quantitative_data, 2, sd, na.rm = TRUE)
Min  <- apply(quantitative_data, 2, min, na.rm = TRUE)
Max  <- apply(quantitative_data, 2, max, na.rm = TRUE)
Q1   <- apply(quantitative_data, 2, quantile, probs = 0.25, na.rm = TRUE)
Q2   <- apply(quantitative_data, 2, quantile, probs = 0.5, na.rm = TRUE)
Q3   <- apply(quantitative_data, 2, quantile, probs = 0.75, na.rm = TRUE)
DTM <- data.frame(Mean, Var, Sd, Min, Max, Q1, Q2, Q3)
View(DTM)